"use strict";
/* Food-V2-Stand 10.1.25: zentraler FOOD_ICON_PATHS-Stamm inklusive freigegebenem FOOD-Aufnahmeblock. */
const FOOD_ICON_PATHS = Object.freeze({
  "karotte": "assets/illustrations-v2/foods/karotte.svg",
  "kartoffel": "assets/illustrations-v2/foods/kartoffel.svg",
  "zucchini": "assets/illustrations-v2/foods/zucchini.svg",
  "rind": "assets/illustrations-v2/foods/rind.svg",
  "brokkoli": "assets/illustrations-v2/foods/brokkoli.svg",
  "banane": "assets/illustrations-v2/foods/banane.svg",
  "hafer": "assets/illustrations-v2/foods/hafer.svg",
  "apfel": "assets/illustrations-v2/foods/apfel.svg",
  "ei": "assets/illustrations-v2/foods/ei.svg",
  "birne": "assets/illustrations-v2/foods/birne.svg",
  "huhn": "assets/illustrations-v2/foods/huhn.svg",
  "hirse": "assets/illustrations-v2/foods/hirse.svg",
  "karfiol": "assets/illustrations-v2/foods/karfiol.svg",
  "suesskartoffel": "assets/illustrations-v2/foods/suesskartoffel.svg",
  "rote-linsen": "assets/illustrations-v2/foods/rote-linsen.svg",
  "erdnuss": "assets/illustrations-v2/foods/erdnuss.svg",
  "weizen": "assets/illustrations-v2/foods/weizen.svg",
  "lachs": "assets/illustrations-v2/foods/lachs.svg",
  "rapsoel": "assets/illustrations-v2/foods/rapsoel.svg",
  "sesam": "assets/illustrations-v2/foods/sesam.svg",
  "erbsen-tk-moeglich": "assets/illustrations-v2/foods/erbsen-tk-moeglich.svg",
  "kuhmilch": "assets/illustrations-v2/foods/kuhmilch.svg",
  "kuerbis": "assets/illustrations-v2/foods/kuerbis.svg",
  "naturjoghurt": "assets/illustrations-v2/foods/naturjoghurt.svg",
  "buttermilch": "assets/illustrations-v2/foods/buttermilch.svg",
  "mais-polenta": "assets/illustrations-v2/foods/mais-polenta.svg",
  "avocado": "assets/illustrations-v2/foods/avocado.svg",
  "kohlrabi": "assets/illustrations-v2/foods/kohlrabi.svg",
  "mango": "assets/illustrations-v2/foods/mango.svg",
  "reis": "assets/illustrations-v2/foods/reis.svg",
  "kichererbse": "assets/illustrations-v2/foods/kichererbse.svg",
  "gruene-bohnen": "assets/illustrations-v2/foods/bohne.svg",
  "papaya": "assets/illustrations-v2/foods/papaya.svg",
  "mungbohne": "assets/illustrations-v2/foods/mungbohne.svg",
  "pflaume": "assets/illustrations-v2/foods/pflaume.svg",
  "pfirsich": "assets/illustrations-v2/foods/pfirsich.svg",
  "pute": "assets/illustrations-v2/foods/pute.svg",
  "gurke": "assets/illustrations-v2/foods/gurke.svg",
  "kabeljau": "assets/illustrations-v2/foods/kabeljau.svg",
  "tomate": "assets/illustrations-v2/foods/tomate.svg",
  "paprika": "assets/illustrations-v2/foods/paprika.svg",
  "heidelbeere": "assets/illustrations-v2/foods/heidelbeere.svg",
  "sellerie": "assets/illustrations-v2/foods/knollensellerie.svg",
  "mandel": "assets/illustrations-v2/foods/mandel.svg",
  "rote-ruebe": "assets/illustrations-v2/foods/rote-ruebe.svg",
  "lauch": "assets/illustrations-v2/foods/lauch.svg",
  "spinat": "assets/illustrations-v2/foods/spinat.svg",
  "quinoa": "assets/illustrations-v2/foods/quinoa.svg",
  "kiwi": "assets/illustrations-v2/foods/kiwi.svg",
  "mandarine": "assets/illustrations-v2/foods/mandarine.svg",
  "schwein": "assets/illustrations-v2/foods/schwein.svg",
  "lamm": "assets/illustrations-v2/foods/lamm.svg",
  "soja-tofu": "assets/illustrations-v2/foods/soja-tofu.svg",
  "roggen": "assets/illustrations-v2/foods/roggen.svg",
  "gerste": "assets/illustrations-v2/foods/gerste.svg",
  "wirsing": "assets/illustrations-v2/foods/wirsing.svg",
  "aubergine": "assets/illustrations-v2/foods/aubergine.svg",
  "walnuss": "assets/illustrations-v2/foods/walnuss.svg",
  "zimt": "assets/illustrations-v2/foods/zimt.svg",
  "rosenkohl": "assets/illustrations-v2/foods/rosenkohl.svg",
  "weisskraut": "assets/illustrations-v2/foods/weisskraut.svg",
  "rotkraut": "assets/illustrations-v2/foods/rotkraut.svg",
  "maroni": "assets/illustrations-v2/foods/maroni.svg",
  "buchweizen": "assets/illustrations-v2/foods/buchweizen.svg",
  "amaranth": "assets/illustrations-v2/foods/amaranth.svg",
  "kaki": "assets/illustrations-v2/foods/kaki.svg",
  "forelle": "assets/illustrations-v2/foods/forelle.svg",
  "weisse-bohnen": "assets/illustrations-v2/foods/weisse-bohnen.svg",
  "zwiebel": "assets/illustrations-v2/foods/zwiebel.svg",
  "knoblauch": "assets/illustrations-v2/foods/knoblauch.svg",
  "petersilie": "assets/illustrations-v2/foods/petersilie.svg",
  "basilikum": "assets/illustrations-v2/foods/basilikum.svg",
  "oregano": "assets/illustrations-v2/foods/oregano.svg",
  "haselnuss": "assets/illustrations-v2/foods/haselnuss.svg",
  "steckruebe": "assets/illustrations-v2/foods/steckruebe.svg",
  "schwarzwurzel": "assets/illustrations-v2/foods/schwarzwurzel.svg",
  "topinambur": "assets/illustrations-v2/foods/topinambur.svg",
  "gelbe-linsen": "assets/illustrations-v2/foods/gelbe-linsen.svg",
  "schwarze-bohnen": "assets/illustrations-v2/foods/schwarze-bohnen.svg",
  "seelachs": "assets/illustrations-v2/foods/seelachs.svg",
  "kokos": "assets/illustrations-v2/foods/kokos.svg",
  "ananas": "assets/illustrations-v2/foods/ananas.svg",
  "granatapfel": "assets/illustrations-v2/foods/granatapfel.svg",
  "sonnenblumenkerne": "assets/illustrations-v2/foods/sonnenblumenkerne.svg",
  "kuerbiskerne": "assets/illustrations-v2/foods/kuerbiskerne.svg",
  "dill": "assets/illustrations-v2/foods/dill.svg",
  "thymian": "assets/illustrations-v2/foods/thymian.svg",
  "majoran": "assets/illustrations-v2/foods/majoran.svg",
  "rosmarin": "assets/illustrations-v2/foods/rosmarin.svg",
  "cashew": "assets/illustrations-v2/foods/cashew.svg",
  "champignon": "assets/illustrations-v2/foods/champignon.svg",
  "pak-choi": "assets/illustrations-v2/foods/pak-choi.svg",
  "okra": "assets/illustrations-v2/foods/okra.svg",
  "schwarze-linsen": "assets/illustrations-v2/foods/schwarze-linsen.svg",
  "melone": "assets/illustrations-v2/foods/melone.svg",
  "guave": "assets/illustrations-v2/foods/guave.svg",
  "drachenfrucht": "assets/illustrations-v2/foods/drachenfrucht.svg",
  "pistazie": "assets/illustrations-v2/foods/pistazie.svg",
  "garnele": "assets/illustrations-v2/foods/garnele.svg",
  "leinsamen": "assets/illustrations-v2/foods/leinsamen.svg",
  "koriandergruen": "assets/illustrations-v2/foods/koriandergruen.svg",
  "kurkuma": "assets/illustrations-v2/foods/kurkuma.svg",
  "ingwer": "assets/illustrations-v2/foods/ingwer.svg",
  "vanille": "assets/illustrations-v2/foods/vanille.svg",
  "wassermelone": "assets/illustrations-v2/foods/wassermelone.svg",
  "orange": "assets/illustrations-v2/foods/orange.svg",
  "erdbeere": "assets/illustrations-v2/foods/erdbeere.svg",
  "himbeere": "assets/illustrations-v2/foods/himbeere.svg",
  "aprikose": "assets/illustrations-v2/foods/aprikose.svg",
  "nudeln-pasta": "assets/illustrations-v2/foods/nudeln-pasta.svg",
  "dinkel": "assets/illustrations-v2/foods/dinkel.svg",
  "saba-banane": "assets/illustrations-v2/foods/saba-banane.svg",
  "upo-flaschenkuerbis": "assets/illustrations-v2/foods/upo-flaschenkuerbis.svg",
  "sayote-chayote": "assets/illustrations-v2/foods/sayote-chayote.svg",
  "patola-ridge-gourd": "assets/illustrations-v2/foods/patola-ridge-gourd.svg",
  "malunggay-moringablaetter": "assets/illustrations-v2/foods/malunggay-moringablaetter.svg",
  "kangkong-wasserspinat": "assets/illustrations-v2/foods/kangkong-wasserspinat.svg",
  "kamote-blaetter": "assets/illustrations-v2/foods/kamote-blaetter.svg",
  "sitaw-lange-bohnen": "assets/illustrations-v2/foods/sitaw-lange-bohnen.svg",
  "gabi-taro": "assets/illustrations-v2/foods/gabi-taro.svg",
  "cassava-kamoting-kahoy": "assets/illustrations-v2/foods/cassava-kamoting-kahoy.svg",
  "ube-violette-yamswurzel": "assets/illustrations-v2/foods/ube-violette-yamswurzel.svg",
  "bangus-milkfish": "assets/illustrations-v2/foods/bangus-milkfish.svg",
  "tilapia": "assets/illustrations-v2/foods/tilapia.svg",
  "galunggong-round-scad": "assets/illustrations-v2/foods/galunggong-round-scad.svg",
  "calamansi": "assets/illustrations-v2/foods/calamansi.svg",
  "pomelo": "assets/illustrations-v2/foods/pomelo.svg",
  "jackfruit-langka": "assets/illustrations-v2/foods/jackfruit-langka.svg",
  "rambutan": "assets/illustrations-v2/foods/rambutan.svg",
  "lanzones": "assets/illustrations-v2/foods/lanzones.svg",
  "chico-sapodilla": "assets/illustrations-v2/foods/chico-sapodilla.svg",
  "guyabano-soursop": "assets/illustrations-v2/foods/guyabano-soursop.svg",
  "caimito-sternapfel": "assets/illustrations-v2/foods/caimito-sternapfel.svg",
  "rimas-brotfrucht": "assets/illustrations-v2/foods/rimas-brotfrucht.svg",
  "saluyot-juteblaetter": "assets/illustrations-v2/foods/saluyot-juteblaetter.svg",
  "senf": "assets/illustrations-v2/foods/senf.svg",
  "stangensellerie": "assets/illustrations-v2/foods/stangensellerie.svg",
  "fenchel": "assets/illustrations-v2/foods/fenchel.svg",
  "pastinake": "assets/illustrations-v2/foods/pastinake.svg",
  "dattel": "assets/illustrations-v2/foods/dattel.svg",
  "kirsche": "assets/illustrations-v2/foods/kirsche.svg",
  "rosine": "assets/illustrations-v2/foods/rosine.svg",
  "traube": "assets/illustrations-v2/foods/traube.svg",
  "zitrone": "assets/illustrations-v2/foods/zitrone.svg",
  "brot": "assets/illustrations-v2/foods/brot.svg",
  "couscous": "assets/illustrations-v2/foods/couscous.svg",
  "haferdrink": "assets/illustrations-v2/foods/haferdrink.svg",
  "polenta": "assets/illustrations-v2/foods/polenta.svg",
  "butter": "assets/illustrations-v2/foods/butter.svg",
  "frischkaese": "assets/illustrations-v2/foods/frischkaese.svg",
  "huettenkaese": "assets/illustrations-v2/foods/huettenkaese.svg",
  "kaese": "assets/illustrations-v2/foods/kaese.svg",
  "kefir": "assets/illustrations-v2/foods/kefir.svg",
  "mozzarella": "assets/illustrations-v2/foods/mozzarella.svg",
  "quark": "assets/illustrations-v2/foods/quark.svg",
  "skyr": "assets/illustrations-v2/foods/skyr.svg",
  "chiasamen": "assets/illustrations-v2/foods/chiasamen.svg",
  "tahin": "assets/illustrations-v2/foods/tahin.svg",
  "kokosoel": "assets/illustrations-v2/foods/kokosoel.svg",
  "olivenoel": "assets/illustrations-v2/foods/olivenoel.svg",
  "sardine": "assets/illustrations-v2/foods/sardine.svg",
  "thunfisch": "assets/illustrations-v2/foods/thunfisch.svg",
  "sojabohne": "assets/illustrations-v2/foods/sojabohne.svg",
  "sojajoghurt": "assets/illustrations-v2/foods/sojajoghurt.svg",
  "kakao": "assets/illustrations-v2/foods/kakao.svg",
  "nektarine": "assets/illustrations-v2/foods/nektarine.svg",
  "brombeere": "assets/illustrations-v2/foods/brombeere.svg",
  "ribisel": "assets/illustrations-v2/foods/ribisel.svg",
  "feige": "assets/illustrations-v2/foods/feige.svg",
  "mangold": "assets/illustrations-v2/foods/mangold.svg",
  "spargel": "assets/illustrations-v2/foods/spargel.svg",
  "petersilienwurzel": "assets/illustrations-v2/foods/petersilienwurzel.svg",
  "weizengriess": "assets/illustrations-v2/foods/weizengriess.svg",
  "bulgur": "assets/illustrations-v2/foods/bulgur.svg",
  "kidneybohne": "assets/illustrations-v2/foods/kidneybohne.svg",
  "braune-gruene-linse": "assets/illustrations-v2/foods/braune-gruene-linse.svg",
  "schnittlauch": "assets/illustrations-v2/foods/schnittlauch.svg",
  "pecannuss": "assets/illustrations-v2/foods/pecannuss.svg",
  "paranuss": "assets/illustrations-v2/foods/paranuss.svg",
  "macadamia": "assets/illustrations-v2/foods/macadamia.svg",
  "lupine": "assets/illustrations-v2/foods/lupine.svg",
  "miesmuschel": "assets/illustrations-v2/foods/miesmuschel.svg",
  "mohn": "assets/illustrations-v2/foods/mohn.svg",
  "tempeh": "assets/illustrations-v2/foods/tempeh.svg",
  "kaeferbohne": "assets/illustrations-v2/foods/kaeferbohne.svg",
  "rhabarber": "assets/illustrations-v2/foods/rhabarber.svg",
  "chinakohl": "assets/illustrations-v2/foods/chinakohl.svg",
  "rucola": "assets/illustrations-v2/foods/rucola.svg",
  "radicchio": "assets/illustrations-v2/foods/radicchio.svg",
  "endivie": "assets/illustrations-v2/foods/endivie.svg",
  "rettich": "assets/illustrations-v2/foods/rettich.svg",
  "blattsalat": "assets/illustrations-v2/foods/blattsalat.svg",
  "holunder": "assets/illustrations-v2/foods/holunder.svg",
  "preiselbeere": "assets/illustrations-v2/foods/preiselbeere.svg",
  "quitte": "assets/illustrations-v2/foods/quitte.svg",
  "kren": "assets/illustrations-v2/foods/kren.svg",
  "walnussoel": "assets/illustrations-v2/foods/walnussoel.svg",
  "sojaoel": "assets/illustrations-v2/foods/sojaoel.svg",
  "weizenkeimoel": "assets/illustrations-v2/foods/weizenkeimoel.svg",
  "honig": "assets/illustrations-v2/foods/honig.svg"
});
const RECIPE_ICON_PATHS = Object.freeze({
  "Obst-Hafer-Pancakes": "assets/illustrations-v2/recipes/obst-hafer-pancakes.svg",
  "Birne-Hirse-Pancakes": "assets/illustrations-v2/recipes/birne-hirse-pancakes.svg",
  "Gemüse-Hafer-Pancakes": "assets/illustrations-v2/recipes/gemuese-hafer-pancakes.svg",
  "Zucchini-Hafer-Pancakes": "assets/illustrations-v2/recipes/zucchini-hafer-pancakes.svg",
  "Ube-Bananen-Pancakes": "assets/illustrations-v2/recipes/ube-bananen-pancakes.svg",
  "Rind-Hafer-Bällchen": "assets/illustrations-v2/recipes/rind-hafer-baellchen.svg",
  "Geflügel-Gemüse-Hafer-Bällchen": "assets/illustrations-v2/recipes/gefluegel-gemuese-hafer-baellchen.svg",
  "Lachs-Kartoffel-Bällchen": "assets/illustrations-v2/recipes/lachs-kartoffel-baellchen.svg",
  "Rote-Linsen-Gemüsebällchen": "assets/illustrations-v2/recipes/rote-linsen-gemuesebaellchen.svg",
  "Tofu-Brokkoli-Bällchen": "assets/illustrations-v2/recipes/tofu-brokkoli-baellchen.svg",
  "Brokkoli-Kartoffel-Taler": "assets/illustrations-v2/recipes/brokkoli-kartoffel-taler.svg",
  "Zucchini-Hafer-Puffer": "assets/illustrations-v2/recipes/zucchini-hafer-puffer.svg",
  "Kichererbsen-Kürbis-Taler": "assets/illustrations-v2/recipes/kichererbsen-kuerbis-taler.svg",
  "Rote-Linsen-Bratlinge": "assets/illustrations-v2/recipes/rote-linsen-bratlinge.svg",
  "Polenta-Zucchini-Sticks": "assets/illustrations-v2/recipes/polenta-zucchini-sticks.svg",
  "Süßkartoffel-Hirse-Sticks": "assets/illustrations-v2/recipes/suesskartoffel-hirse-sticks.svg",
  "Omelettstreifen": "assets/illustrations-v2/recipes/omelettstreifen.svg",
  "Zucchini-Omelett": "assets/illustrations-v2/recipes/zucchini-omelett.svg",
  "Obst-Haferbrei": "assets/illustrations-v2/recipes/obst-haferbrei.svg",
  "Obst-Hirsebrei": "assets/illustrations-v2/recipes/obst-hirsebrei.svg",
  "Obst-Polentabrei": "assets/illustrations-v2/recipes/obst-polentabrei.svg",
  "Obst-Reisbrei": "assets/illustrations-v2/recipes/obst-reisbrei.svg",
  "Obst-Quinoabrei": "assets/illustrations-v2/recipes/obst-quinoabrei.svg",
  "Obst-Buchweizenbrei": "assets/illustrations-v2/recipes/obst-buchweizenbrei.svg",
  "Obst-Grießbrei": "assets/illustrations-v2/recipes/obst-griessbrei.svg",
  "Milch-Getreide-Brei": "assets/illustrations-v2/recipes/milch-getreide-brei.svg",
  "Baby-Bananenbrot": "assets/illustrations-v2/recipes/baby-bananenbrot.svg",
  "Kürbis-Hafer-Brei": "assets/illustrations-v2/recipes/kuerbis-hafer-brei.svg",
  "Gemüse-Nudel-Sauce": "assets/illustrations-v2/recipes/gemuese-nudel-sauce.svg",
  "Baby-Linsen-Bolognese": "assets/illustrations-v2/recipes/baby-linsen-bolognese.svg",
  "Lugaw-Basis": "assets/illustrations-v2/recipes/lugaw-basis.svg",
  "Kürbis-Lugaw": "assets/illustrations-v2/recipes/kuerbis-lugaw.svg",
  "Monggo-Kalabasa-Brei": "assets/illustrations-v2/recipes/monggo-kalabasa-brei.svg",
  "Tinola-inspiriert": "assets/illustrations-v2/recipes/tinola-inspiriert.svg",
  "Arroz-caldo-inspiriert": "assets/illustrations-v2/recipes/arroz-caldo-inspiriert.svg",
  "Kalabasa mit Kokos": "assets/illustrations-v2/recipes/kalabasa-mit-kokos.svg",
  "Tilapia-Reis-Brei": "assets/illustrations-v2/recipes/tilapia-reis-brei.svg",
  "Bangus-Kartoffel-Taler": "assets/illustrations-v2/recipes/bangus-kartoffel-taler.svg",
  "Obst-Hafer-Muffins": "assets/illustrations-v2/recipes/obst-hafer-muffins.svg",
  "Gemüse-Hafer-Muffins": "assets/illustrations-v2/recipes/gemuese-hafer-muffins.svg",
  "Kürbis-Hirse-Muffins": "assets/illustrations-v2/recipes/kuerbis-hirse-muffins.svg",
  "Karotten-Polenta-Brei": "assets/illustrations-v2/recipes/karotten-polenta-brei.svg",
  "Süßkartoffel-Rote-Linsen-Brei": "assets/illustrations-v2/recipes/suesskartoffel-rote-linsen-brei.svg",
  "Zucchini-Quinoa-Brei": "assets/illustrations-v2/recipes/zucchini-quinoa-brei.svg",
  "Kichererbsenmehl-Zucchini-Taler": "assets/illustrations-v2/recipes/kichererbsenmehl-zucchini-taler.svg",
  "Bananen-Haferbrei mit Erdnussmus": "assets/illustrations-v2/recipes/bananen-haferbrei-mit-erdnussmus.svg",
  "Karotten-Hirse-Brei mit Tahin": "assets/illustrations-v2/recipes/karotten-hirse-brei-mit-tahin.svg",
  "Apfel-Hirse-Brei mit Mandelmus": "assets/illustrations-v2/recipes/apfel-hirse-brei-mit-mandelmus.svg",
  "Apfel-Birnen-Kompott": "assets/illustrations-v2/recipes/apfel-birnen-kompott.svg",
  "Karotte-Süßkartoffel-Brei": "assets/illustrations-v2/recipes/karotte-suesskartoffel-brei.svg",
  "Brokkoli-Kartoffel-Stampf": "assets/illustrations-v2/recipes/brokkoli-kartoffel-stampf.svg",
  "Karfiol-Kartoffel-Stampf": "assets/illustrations-v2/recipes/karfiol-kartoffel-stampf.svg",
  "Zucchini-Kartoffel-Brei": "assets/illustrations-v2/recipes/zucchini-kartoffel-brei.svg",
  "Erbsen-Kartoffel-Stampf": "assets/illustrations-v2/recipes/erbsen-kartoffel-stampf.svg",
  "Kürbis-Linsen-Suppe": "assets/illustrations-v2/recipes/kuerbis-linsen-suppe.svg",
  "Mildes Rote-Linsen-Dhal": "assets/illustrations-v2/recipes/mildes-rote-linsen-dhal.svg",
  "Huhn-Karotte-Nudel-Topf": "assets/illustrations-v2/recipes/huhn-karotte-nudel-topf.svg",
  "Huhn-Lauch-Kartoffel-Topf": "assets/illustrations-v2/recipes/huhn-lauch-kartoffel-topf.svg",
  "Huhn-Brokkoli-Reis": "assets/illustrations-v2/recipes/huhn-brokkoli-reis.svg",
  "Rind-Gemüse-Bolognese": "assets/illustrations-v2/recipes/rind-gemuese-bolognese.svg",
  "Tomaten-Linsen-Sauce": "assets/illustrations-v2/recipes/tomaten-linsen-sauce.svg",
  "Brokkoli-Linsen-Pasta": "assets/illustrations-v2/recipes/brokkoli-linsen-pasta.svg",
  "Gemüse-Pasta mit Zucchini und Tomate": "assets/illustrations-v2/recipes/gemuese-pasta-mit-zucchini-und-tomate.svg",
  "Lachs-Reis-Erbsen": "assets/illustrations-v2/recipes/lachs-reis-erbsen.svg",
  "Lachs-Süßkartoffel-Stampf": "assets/illustrations-v2/recipes/lachs-suesskartoffel-stampf.svg",
  "Kabeljau-Tomaten-Gemüse": "assets/illustrations-v2/recipes/kabeljau-tomaten-gemuese.svg",
  "Weiches Rührei": "assets/illustrations-v2/recipes/weiches-ruehrei.svg",
  "Eier-Finger": "assets/illustrations-v2/recipes/eier-finger.svg",
  "Paprika-Omelettstreifen": "assets/illustrations-v2/recipes/paprika-omelettstreifen.svg",
  "Ei-Champignon-Cups": "assets/illustrations-v2/recipes/ei-champignon-cups.svg",
  "Hummus mit weichen Gemüsesticks": "assets/illustrations-v2/recipes/hummus-mit-weichen-gemuesesticks.svg",
  "Kürbis-Kichererbsen-Creme": "assets/illustrations-v2/recipes/kuerbis-kichererbsen-creme.svg",
  "Avocado-Bananen-Creme": "assets/illustrations-v2/recipes/avocado-bananen-creme.svg",
  "Buchweizen-Bananen-Pancakes": "assets/illustrations-v2/recipes/buchweizen-bananen-pancakes.svg",
  "Süßkartoffel-Linsen-Taler": "assets/illustrations-v2/recipes/suesskartoffel-linsen-taler.svg",
  "Tofu-Zucchini-Reis": "assets/illustrations-v2/recipes/tofu-zucchini-reis.svg",
  "Gebackene Saba-Banane": "assets/illustrations-v2/recipes/gebackene-saba-banane.svg",
  "Huhn-Lugaw": "assets/illustrations-v2/recipes/huhn-lugaw.svg",
  "Sayote-Huhn-Reis": "assets/illustrations-v2/recipes/sayote-huhn-reis.svg",
  "Monggo-Süßkartoffel-Brei": "assets/illustrations-v2/recipes/monggo-suesskartoffel-brei.svg",
  "Ube-Hafer-Brei": "assets/illustrations-v2/recipes/ube-hafer-brei.svg",
  "Obst-Joghurt": "assets/illustrations-v2/recipes/obst-joghurt.svg",
  "Obst-Hafer-Joghurt": "assets/illustrations-v2/recipes/obst-hafer-joghurt.svg",
  "Obst-Hirse-Joghurt": "assets/illustrations-v2/recipes/obst-hirse-joghurt.svg",
  "Obst-Grieß-Joghurt": "assets/illustrations-v2/recipes/obst-griess-joghurt.svg",
  "Buttermilch-Hafer-Obstbrei": "assets/illustrations-v2/recipes/buttermilch-hafer-obstbrei.svg",
  "Buttermilch-Hirse-Obstbrei": "assets/illustrations-v2/recipes/buttermilch-hirse-obstbrei.svg",
  "Buttermilch-Grieß-Obstbrei": "assets/illustrations-v2/recipes/buttermilch-griess-obstbrei.svg",
  "Joghurt-Nussmus-Miniportion": "assets/illustrations-v2/recipes/joghurt-nussmus-miniportion.svg",
  "Bananen-Joghurt-Hafer-Pancakes": "assets/illustrations-v2/recipes/bananen-joghurt-hafer-pancakes.svg",
  "Obst-Joghurt-Hafer-Ofenbites": "assets/illustrations-v2/recipes/obst-joghurt-hafer-ofenbites.svg",
  "Zucchini-Joghurt-Hafer-Bites": "assets/illustrations-v2/recipes/zucchini-joghurt-hafer-bites.svg",
  "Joghurt-Hafer-Waffeln": "assets/illustrations-v2/recipes/joghurt-hafer-waffeln.svg",
  "Weiche Joghurt-Fladen": "assets/illustrations-v2/recipes/weiche-joghurt-fladen.svg",
  "Gemüse-Joghurt-Mini-Muffins": "assets/illustrations-v2/recipes/gemuese-joghurt-mini-muffins.svg",
  "Huhn-Gemüse-Muffins": "assets/illustrations-v2/recipes/huhn-gemuese-muffins.svg",
  "Süßkartoffel-Linsen-Muffins": "assets/illustrations-v2/recipes/suesskartoffel-linsen-muffins.svg",
  "Fleisch-Gemüse-Bällchen": "assets/illustrations-v2/recipes/fleisch-gemuese-baellchen.svg",
  "Gemüse-Fleisch-Nockerl": "assets/illustrations-v2/recipes/gemuese-fleisch-nockerl.svg",
  "Bohnen-Kartoffel-Stampf": "assets/illustrations-v2/recipes/bohnen-kartoffel-stampf.svg"
});

const FOOD_CATEGORY_FALLBACK_PATHS = Object.freeze({
  "Gemüse": "assets/illustrations/fallbacks/gemuese.svg",
  "Obst": "assets/illustrations/fallbacks/obst.svg",
  "Getreide/Stärke": "assets/illustrations/fallbacks/getreide-staerke.svg",
  "Hülsenfrucht": "assets/illustrations/fallbacks/huelsenfrucht.svg",
  "Fleisch": "assets/illustrations/fallbacks/fleisch.svg",
  "Fisch": "assets/illustrations/fallbacks/fisch.svg",
  "Milchprodukt": "assets/illustrations/fallbacks/milchprodukt.svg",
  "Ei": "assets/illustrations/fallbacks/ei.svg",
  "Nuss": "assets/illustrations/fallbacks/nuss.svg",
  "Samen": "assets/illustrations/fallbacks/samen.svg",
  "Kraut/Gewürz": "assets/illustrations/fallbacks/kraut-gewuerz.svg",
  "Wurzel/Knolle": "assets/illustrations/fallbacks/wurzel-knolle.svg"
});
const FOOD_GENERIC_FALLBACK_PATH = "assets/illustrations/fallbacks/generisch.svg";
function foodIllustrationPath(f){
  if(!f) return FOOD_GENERIC_FALLBACK_PATH;
  return FOOD_ICON_PATHS[f.id] || FOOD_CATEGORY_FALLBACK_PATHS[f.category] || FOOD_GENERIC_FALLBACK_PATH;
}
const ILLUSTRATION_V2_PREFIX = "assets/illustrations-v2/";
function isV2IllustrationPath(src){
  return String(src||"").replace(/^\.\//,"").startsWith(ILLUSTRATION_V2_PREFIX);
}
function illustrationMissingMarkup(label,kind="food"){
  console.error(`[Illustrationen] Fehlende ${kind}-Illustration:`,label);
  return `<span class="illustration-missing" role="img" aria-label="Illustration für ${esc(label)} fehlt">!</span>`;
}
const ILLUSTRATION_ASSET_REVISION = "10.1.25";
function revisionedIllustrationSrc(src){ return `${src}${String(src).includes("?") ? "&" : "?"}v=${ILLUSTRATION_ASSET_REVISION}`; }
function illustrationImg(src,label,kind="food"){
  if(!src) return illustrationMissingMarkup(label,kind);
  const assetSrc=revisionedIllustrationSrc(src);
  if(isV2IllustrationPath(src)){
    return `<span class="illustration-icon illustration-icon--${kind} item-illustration ${kind}-illustration" aria-hidden="true"><img class="illustration-icon__asset" src="${assetSrc}" alt="" aria-hidden="true" loading="lazy" decoding="async" data-illustration-label="${esc(label)}" data-illustration-kind="${kind}"></span>`;
  }
  return `<img class="item-illustration ${kind}-illustration" src="${assetSrc}" alt="" aria-hidden="true" loading="lazy" decoding="async">`;
}
function foodIconSvg(foodOrId){ const f=typeof foodOrId==="string" ? (food(foodOrId)||FOOD_DB.find(x=>x.id===foodOrId)) : foodOrId; return illustrationImg(foodIllustrationPath(f),f?.name||"unbekanntes Lebensmittel","food"); }
function recipeIconSvg(recipeOrName){ const r=typeof recipeOrName==="string" ? RECIPES.find(x=>x.name===recipeOrName) : recipeOrName; return illustrationImg(r&&RECIPE_ICON_PATHS[r.name],r?.name||String(recipeOrName||"unbekanntes Rezept"),"recipe"); }
function foodIllustrationUsesFallback(f){
  const src=foodIllustrationPath(f);
  return !src || src===FOOD_GENERIC_FALLBACK_PATH || src===FOOD_CATEGORY_FALLBACK_PATHS[f?.category];
}
function auditIllustrationCoverage(){ return {foodsMissing:FOOD_DB.filter(foodIllustrationUsesFallback).map(f=>f.name),recipesMissing:RECIPES.filter(r=>!RECIPE_ICON_PATHS[r.name]).map(r=>r.name),foodCount:FOOD_DB.length,recipeCount:RECIPES.length}; }
document.addEventListener("error",event=>{
  const img=event.target;
  if(!img || !img.classList || !img.classList.contains("illustration-icon__asset")) return;
  const wrapper=img.closest(".illustration-icon");
  if(!wrapper) return;
  wrapper.outerHTML=illustrationMissingMarkup(img.dataset.illustrationLabel||"unbekannte Illustration",img.dataset.illustrationKind||"food");
},true);
document.addEventListener("DOMContentLoaded",()=>{ const audit=auditIllustrationCoverage(); if(audit.foodsMissing.length||audit.recipesMissing.length) console.error("[Illustrationen] Abdeckung unvollständig",audit); });